// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package setup

import (
	"campushelphub/api/common"
	"campushelphub/api/frontend"
	"campushelphub/api/handlerset"
	"campushelphub/internal/common/RSA"
	"campushelphub/internal/common/auth"
	"campushelphub/internal/common/snowflake"
	"campushelphub/internal/config"
	"campushelphub/internal/errors"
	"campushelphub/internal/log"
	"campushelphub/internal/repository"
	"campushelphub/internal/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp() *App {
	errorsError := errors.NewError()
	logger := log.NewLogger()
	handler := common.NewHandler(errorsError, logger)
	configConfig := config.NewConfig()
	db := repository.NewDB(configConfig)
	userRepository := repository.NewMySQLUserRepository(db)
	iDgenarator := snowflake.NewSnowflakeIDGenerator(configConfig)
	tokenManager := auth.NewTokenManager(configConfig)
	userService := service.NewUserService(userRepository, iDgenarator, tokenManager)
	wechatService := service.NewWechatService(configConfig, errorsError)
	chromeService := service.NewChromeService(configConfig, errorsError)
	rsa := RSA.NewRSA(configConfig)
	userHandler := frontend.NewUserHandler(handler, userService, wechatService, tokenManager, chromeService, rsa)
	encryptionHandler := frontend.NewEncryptionHandler(handler, errorsError, logger, rsa)
	handlerSet := handlerset.NewHandlerSet(userHandler, encryptionHandler)
	engine := NewEngine(handlerSet, tokenManager, logger)
	app := NewApp(engine, configConfig, db)
	return app
}

// wire.go:

var ErrorSet = wire.NewSet(errors.NewError)

var ConfigSet = wire.NewSet(config.NewConfig)

var DBSet = wire.NewSet(repository.NewDB)

var TokenManagerSet = wire.NewSet(auth.NewTokenManager)

var RSASet = wire.NewSet(RSA.NewRSA)

var RepositorySet = wire.NewSet(repository.NewMySQLUserRepository)

var ServiceSet = wire.NewSet(service.NewUserService, service.NewChromeService, service.NewWechatService)

var BaseHandlerSet = wire.NewSet(common.NewHandler)

var LoggerSet = wire.NewSet(log.NewLogger)

var HandlerSet = wire.NewSet(handlerset.NewHandlerSet)

var FrontendHandlerSet = wire.NewSet(frontend.NewUserHandler, frontend.NewEncryptionHandler)

var EngineSet = wire.NewSet(
	NewEngine,
)

var AppSet = wire.NewSet(
	NewApp,
)

var IDGenSet = wire.NewSet(snowflake.NewSnowflakeIDGenerator)
